[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
contract = "2gJwfKpPfhn1NUL4iHw5y4Di5rDtVuQgoVmAP7zN9oo5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/taoyiran/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
